### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ketanchoyal** [Lucs1590/Nkocr#133]
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?export=download&id=1qGe5Zq8VzGxU90Kpt3fUb4noBBywUGuw

**Comment by Lucs1590** [comment]
Thank you, @ketanchoyal! You're right.
Probably I changed the folder structure, so the link changed too.
 
I'll organize this links and update the code!

Once again, thanks for your thoughts! :smiley:
