### ISSUE TITLE
Class name convention python

### ISSUE THREAD

**Issue by AlvaroCavalcante** [Lucs1590/Nkocr#17]
I noticed that ocr_table.py and ocr_product.py has a wrong class naming convention, It must be in CapWords but are in snake case. 
![image](https://user-images.githubusercontent.com/37350513/91049095-0f04ae00-e5f3-11ea-9bbb-08ef5b985af8.png)

Ref: https://www.datacamp.com/community/tutorials/pep8-tutorial-python-code?utm_source=adwords_ppc&utm_campaignid=1455363063&utm_adgroupid=65083631748&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=332602034364&utm_targetid=dsa-429603003980&utm_loc_interest_ms=&utm_loc_physical_ms=1001720&gclid=EAIaIQobChMInI21_PWz6wIVko3ICh3lgQZ2EAAYASAAEgKA2fD_BwE

**Comment by Lucs1590** [comment]
Nice, I will change it and I will use this Issue to make a pylint refactoring. Okay?
