### ISSUE TITLE
Publish package on conda

### ISSUE THREAD

**Issue by Lucs1590** [Lucs1590/Nkocr#188]
**Is your feature request related to a problem? Please describe.**
An excellent alternative to pip is related to the use of conda, so we could add this package on conda.

**Describe the solution you'd like**
Publishing NKOcr Python Package on conda and conda-forge

**Describe alternatives you've considered**
Publish a docker image.

**Additional context**
- https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf
- https://medium.com/@furkankizilay/end-to-end-machine-learning-project-using-fastapi-streamlit-and-docker-6fda32d25c5d

**Comment by Lucs1590** [comment]
@renanzulian try to do it!

**Comment by renanzulian** [comment]
Hi my dear @Lucs1590 

I'm going to solve this one over the week.

**Comment by renanzulian** [comment]
@Lucs1590 

I guess you are supposed to deliver in two ways, but they are different to implement.

The conda users just need the package and will interact with nkocr by importing the package.
On other hand, the docker user is looking to use the nkocr as a service and will deal with the package by a protocol (HTTP ?).

In the docker case, we will need to create a layer to deliver our function as an HTTP resource, but for conda we just need to wrap up what we already have.

I'm going to solve the conda needs, but if you are planning to also deliver as a service let's create a new issue.

**Comment by Lucs1590** [comment]
Sounds good, @renanzulian !
I think that it's enough!

**Comment by renanzulian** [comment]
The PR is opened. Let me know if you need anything.

You are going to need the ANACONDA_TOKEN env variable in the project with a token from anaconda. You can create your own account or use what I sent you.

**Comment by Lucs1590** [comment]
#192
