### ISSUE TITLE
No such file or directory: './src/dictionary/dictionary.pkl' when running OcrTable() with spell_corrector = True

### ISSUE THREAD

**Issue by KiprasKancys** [Lucs1590/Nkocr#221]
**Describe the bug**
Running OcrTable with spell_corrector = True gives an error No such file or directory: './src/dictionary/dictionary.pkl'

**To Reproduce**

```python
from nkocr import OcrTable

text = OcrTable("https://www.fda.gov/files/Nutrition-Facts-Label-Education-Campaign.png", spell_corrector = True)
```

Probably caused by:

https://github.com/Lucs1590/Nkocr/blob/master/src/auxiliary.py#L647

Package was install with pip, I think if I clone the repo I can make it work, but still worth fixing for the future users.

**Comment by Lucs1590** [comment]
@KiprasKancys Thank you very much for your issue. I tried to use the new Github feature ([Copilot Workspace](https://githubnext.com/projects/copilot-workspace)) and by downloading it via pip we were able to solve the problem mentioned, so I will leave the issue as resolved. However, if you still have questions or find something in the project that could be improved, feel free to write again or even open a new issue.

As of version v2.5.1 the feature is fixed, so update your package using the following command:

```bash
pip install nkocr --upgrade
```
