### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by mbrissier** [Lucs1590/Nkocr#66]
Hey,
great work and very interesting project. I try to develop a project for the same purpose as well. The only difference is that I like to read in german nutritional facts. 

So I came across your project and tried to install and used it. The text results were kind of strange to me. I used it like this:

`text = OcrTable(image, language='deu')`
Should I also use:
`                 spell_corrector: bool = False,
                 show_performace: bool = False`
Or should that be True?

I used text.text to get the results. So overall I think it needs a bit more of documentation. 
Thanks in advance

**Comment by Lucs1590** [comment]
Very nice comment @mbrissier !
i think that with you want use another language, you will need to install that language to your environment as well.

You're correct inserting the "deu" on language, but look here:
https://github.com/Lucs1590/Nkocr/blob/b5dc800c0d869df2c5bd8629c76bfd272f61bdcb/.github/workflows/python-app.yml#L30 , for example.

When I used the Github Actions (DevOps) I need to install  ```tesseract-ocr-por```  too.

Try running:
`sudo apt install tesseract-ocr libtesseract-dev tesseract-ocr-deu`

And then, run the scripts again!

I'll try to improve the documentation too!!
Thanks for this issue!!

**Comment by Lucs1590** [comment]
I think this problem can be closed by looking at this commit https://github.com/Lucs1590/Nkocr/commit/6d7c60bb894677f7aeec7337c97e3efc620465d6 .
